### PR TITLE
v1.0

### LINKED ISSUE #29: Missing icon packs
Hey, first of all, thanks for making this, this makes working with icons much easier for me.

Would it be possible to update `@iconify/json`?
https://github.com/natemoo-re/astro-icon/blob/d2e7fafe79369df19f79fe120e00fc829c27ab62/packages/service/package.json#L21-L25

I want to use an icon added in a newer version of a pack but `@iconify/json` is not on the latest version here.

### LINKED ISSUE #35: `svgo` and SSR
`svgo` is a Node.js-only package, thus, it doesn't work in the brand-new environments that Astro SSR supports (e.g. Netlify/Vercel Edge, Deno, Cloudflare workers).

Is there any other option that supports more environments? Or there could be a way to disable svgo altogether so Astro can build successfully?

### LINKED ISSUE #38: Using a custom path for local icons instead of `/src/icons`?
It looks like `/src/icons` is hardcoded into the loader:

https://github.com/natemoo-re/astro-icon/blob/4cfc1badfb5978829c1dfeb5b56491238a3a8e74/packages/core/lib/utils.ts#L189

It would be nice if this was configurable. :)

Specifically I'd like to import from `/public`, if possible.

### LINKED ISSUE #43: Simplify `Props` with ` astroHTML.JSX.SVGAttributes`
Hello!

Maybe this:

```
/// <reference types="astro/astro-jsx" />

export interface Props extends astroHTML.JSX.SVGAttributes {
 ...
}
```

Could now simplify the `Props` part of this component? With the benefit of Astro ecosystem homogenization.

### LINKED ISSUE #54: Offline mode
I am using a build system for reproducible builds. This does not allow for internet access under normal circumstances.

I can circumvent this restriction by offloading the internet access to other buildsteps, though these are required to have a fixed output then.

Therefore I'd like to maintain a list of SVGs to be used in an extra file and using that to "prefetch" them into a cache location and then just tell `astr-icon` which cache folder to use, such that I can still use `name="mdi:account"` or `pack="mdi" name="account"` syntaxes.

Adding just names like that to a list is much easier and less error prone to me, than having to manually copy the SVGs to `/src/icons`, also the necessary rename on filesystem and in code takes removes the relationship to the website that `mdi:account` gives me.

### LINKED ISSUE #65: Updating to `svgo@3` causes issues
I updated `astro-compress` to its latest `1.1.1` release and this broke icons as it brought with it `svgo@3`. Not fully sure it's an issue with `astro-icon`, might very likely be upstream at Astro itself, but I cannot guarantee it...

This made a change on the `cleanupIDs` plugin, which is now called `cleanupIds`.

I have now pinned `astro-compress` to 1.0.12 especially as the `1.1` feature wasn't of interest in my case, but it might be worth updating this package to support `svgo@3`.

Reference for `svgo@3`: https://github.com/svg/svgo/releases/tag/v3.0.0.

```
file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:1746
      throw new Error(`[astro-icon] Unable to load icon "${name}"!
            ^

Error: [astro-icon] Unable to load icon "wifi-slash-regular"!
Error: Unknown builtin plugin "cleanupIDs" specified.
    at file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:1746:13
    at async renderToIterable (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:745:21)
    at async renderAstroComponentInline (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:973:24)
    at async renderChild (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:671:5)
    at async AstroComponent.[Symbol.asyncIterator] (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:703:7)
    at async renderAstroComponent (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:714:20)
    at async renderAstroComponentInline (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:974:9)
    at async renderChild (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:671:5)
    at async AstroComponent.[Symbol.asyncIterator] (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:703:7)
    at async renderAstroComponent (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:714:20)
```

### LINKED ISSUE #68: Allow svgs with titles to keep them after svgo optimization
Thanks for this plugin! I have a suggestion:

It looks like svgo's removeTitle plugin is [enabled by default](https://github.com/natemoo-re/astro-icon/search?q=removeTitle).

While I learned from #36 that there is a prop for _adding_ a title to an svg, I think it would be helpful to permit svg's that already have a title embedded to _keep_ their titles, without needing to re-add them.

Perhaps either svgo's removeTitle plugin could be optionally disabled, or perhaps there could be a prop for astro-icon to preserve any already-existing title?

### LINKED ISSUE #71: Move "[astro-icon] No sprites found ..." warnings to debug level
## Context

It is therefore good to have deep insights what is going on inside astro-icon package, but it could be opted-out by default, and possible to opt-in when needed.

Currently astro-icon does `console.log` for warning:
https://github.com/natemoo-re/astro-icon/blob/c0cc7a703a19ead8c17cdd8e5a8532b5c62405fc/packages/core/lib/context.ts#L23

Astro (and Vite) does a good job by utilising https://github.com/debug-js/debug package, so any debugging can be revealed with `DEBUG=...` variable.

During `astro build` we do get many occurencies of:
```
[astro-icon] No sprites found while rendering "..."
```
even though sprites are used in only one page in whole project. Getting so many messages seems simply excessive.

## TODO

- Move debugging related messages to be opt-out by default, but possible to reveal on demand

### LINKED ISSUE #73: Upgrade to @iconify/utils because @iconify/json-tools is depreciated
Upgrade to [@iconify/utils](https://www.npmjs.com/package/@iconify/utils) because [@iconify/json-tools](https://www.npmjs.com/package/@iconify/json-tools) is depreciated on npm and no longer recommended. Not updated in last two years. This causes so many bugs in the plugin itself. I guess most issues will be fixed once upgraded. 

CleanShot 2022-12-18 at 18 42 50@2x

### LINKED ISSUE #87: The future of `astro-icon`
Hey y'all! Sorry I haven't been on top of the maintenance here.

`astro` looked very different back when the first version of `astro-icon` was built. There was no integration system and SSR was just an idea we had. As such, the current version of `astro-icon` makes some assumptions about your project that are no longer true.

I've started working on a new version of `astro-icon` that will:
- be a proper integration
- support SSR
- not use `svgo` at runtime
- not rely on a custom API service
- have a peer dependency on `@iconify/json` so you can always keep it in sync
- have much better error messages
- 

If you're interested, here's a StackBlitz with my initial exploration. I plan to move this into a branch and work towards a `v1` of `astro-icon` in the coming weeks.

If you'd like to get involved, please reach out on the Astro Discord!

https://github.com/natemoo-re/astro-icon/tree/v1

### PR DESCRIPTION
**Pull request by natemoo-re**
Finally, `astro-icon@1.0.0` is here! This release provides a more flexible and reliable method of icon management, removes a number of redundant APIs, and now relies on Astro's official integration API.

Please see the [Upgrade to `astro-icon` v1](https://github.com/natemoo-re/astro-icon/tree/v1/docs/migrate-to-v1.md) guide for specific migration steps and [the package README](https://github.com/natemoo-re/astro-icon/tree/v1/packages/core#astro-icon) for more information.

MASSIVE thank you to @stramel for keeping this effort alive while I was too burned out to help.

---

Closes #87, closes #71, fixes #29, fixes #35, resolves #38, resolves #43, resolves #54, resolves #65, resolves #68, resolves #73

### CODE REVIEW

**Comment by nimser** [comment]
No insights, but how does that solve #29 ? I'm still missing icons, e.g. `bi:balloon-heart-fill`.

**Comment by Lunarequest** [comment]
hi so i tried using this with my project and discovered that this pr uses pnpm, yarn 2.x will not be able to install this package if it uses pnpm as yarn does not yet have a resolver for pnpm packages

**Comment by stramel** [comment]
Thanks for the feedback @Lunarequest! We should hopefully have an alpha release here soon which will resolve the install problem for you.

**Comment by Lunarequest** [comment]
> Thanks for the feedback @Lunarequest! We should hopefully have an alpha release here soon which will resolve the install problem for you.

thank you!

**Comment by alexanderniebuhr** [comment]
@stramel I was trying to install it via URL this https://gitpkg.now.sh/natemoo-re/astro-icon/packages/core?v1
While it does install, running `astro dev` would not work. Would be great if you can either release an preview version to npm or let me know how to install this branch and test it :)

```
Failed to resolve entry for package "astro-icon". The package may have incorrect main/module/exports specified in its package.json.

**Comment by stramel** [comment]
> @stramel I was trying to install it via URL this [gitpkg.now.sh/natemoo-re/astro-icon/packages/core?v1](https://gitpkg.now.sh/natemoo-re/astro-icon/packages/core?v1) While it does install, running `astro dev` would not work. Would be great if you can either release an preview version to npm or let me know how to install this branch and test it :)
> 
> ```
> Failed to resolve entry for package "astro-icon". The package may have incorrect main/module/exports specified in its package.json.
> ```

Yes, we are wanting to get a prerelease on NPM so that people can start giving it a shot without the workaround. I unfortunately don't have the ability to release. The `v1` branch doesn't have the built code published on it so it won't work. However the code state is in nearly the same spot as my `ms/v1` branch that I previously posted about using. So you should be able to use that branch still.

**Comment by FineWolf** [comment]
> The `v1` branch doesn't have the built code published on it so it won't work.

Would it be possible to add a `prepare` that would run `build` if the dist files are not present? That way we can install from `git`.

**Comment by natemoo-re** [comment]
Thanks for you patience everyone! Happy to say that `astro-icon@next` is published so you can try it out locally!

We have some docs and migration guides to write, so keep an eye out for those. Hoping to wrap this major upgrade up soon.

**Comment by FineWolf** [comment]
@natemoo-re Thanks for your hard work.

Just used `astro-icon@next` on two production websites, and had no issues. Both leveraged `iconify-json` packs and local icons.

**Comment by alexanderniebuhr** [comment]
Used it and figured it added 700kb to the bundled output.. This will break limits for the 1MB in Cloudflare e.g. 
Does it not tree-shake unused icons from iconify? :O

**Comment by stramel** [comment]
@alexanderniebuhr oof... That doesn't sound correct. Can you provide any details or links to the different build before and after? Would love to help resolve this. We actually are deduping icons now so it should result in a much smaller build.

**Comment by alexanderniebuhr** [comment]
> Can you provide any details or links to the different build before and after?

https://gist.github.com/alexanderniebuhr/14603b653ceeb3be2a72dfcc482903e8

Please let me know if you need anything else, I'm currently trying to get a diff.

**Comment by stramel** [comment]
Thank you for the details! I think I understand the issue. I will work on a resolution for this.

**Comment by stramel** [comment]
@alexanderniebuhr Confirmed the issue lies within the SSR while specifying `'*'`. Working on a solution that will remove this DX and bundling issue.

**Comment by alexanderniebuhr** [comment]
> Working on a solution that will remove this DX and bundling issue.

Any update, can I test another version?

**Comment by FDiskas** [comment]
@natemoo-re - everything is ok?

**Comment by stramel** [comment]
> @natemoo-re - everything is ok?

Sorry for the absence on here. We're currently not happy with the SSR DX story here. We're looking into a better fix. 

In the meantime, @natemoo-re proposed core integration with icons within Astro. We will likely need to revist the v1 version once the direction has been decided upon.

**Comment by natemoo-re** [comment]
OK the issues here are stacking up, I know folks are waiting for fixes. 

I'm definitely not happy with the SSR story at the moment, but including `svgo` at runtime seems to be the cause of the vast majority of problems with the current approach. This version at least solves that.

I think I might have an idea for how to move forward here while still supporting the remote icon service, but refactoring the service to be self-updating so it doesn't require as much maintenance from my end. The dynamic nature of this package is a huge part of the appeal. Ideally, SSR users could still use a string and hit the remote service, but if latency is a critical concern for them, they can switch to the local approach.

At the same time, I have proposed for SVG support to be built into Astro and that seems to be something everyone is interested in. But in the meantime I should get this v1.0 out. Hopefully it informs Astro's native approach.

**Pull request merged**
