### PR TITLE
Upgrade SVGO to v3

### LINKED ISSUE #65: Updating to `svgo@3` causes issues
I updated `astro-compress` to its latest `1.1.1` release and this broke icons as it brought with it `svgo@3`. Not fully sure it's an issue with `astro-icon`, might very likely be upstream at Astro itself, but I cannot guarantee it...

This made a change on the `cleanupIDs` plugin, which is now called `cleanupIds`.

I have now pinned `astro-compress` to 1.0.12 especially as the `1.1` feature wasn't of interest in my case, but it might be worth updating this package to support `svgo@3`.

Reference for `svgo@3`: https://github.com/svg/svgo/releases/tag/v3.0.0.

```
file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:1746
      throw new Error(`[astro-icon] Unable to load icon "${name}"!
            ^

Error: [astro-icon] Unable to load icon "wifi-slash-regular"!
Error: Unknown builtin plugin "cleanupIDs" specified.
    at file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:1746:13
    at async renderToIterable (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:745:21)
    at async renderAstroComponentInline (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:973:24)
    at async renderChild (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:671:5)
    at async AstroComponent.[Symbol.asyncIterator] (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:703:7)
    at async renderAstroComponent (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:714:20)
    at async renderAstroComponentInline (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:974:9)
    at async renderChild (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:671:5)
    at async AstroComponent.[Symbol.asyncIterator] (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:703:7)
    at async renderAstroComponent (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:714:20)
```

### LINKED ISSUE #72: Error: Unknown builtin plugin "cleanupIDs" specified.
Hello,

since now I can't build my astro project anymore.
I get the following error:
```error
 error   [astro-icon] Unable to load icon "carbon:phone-filled"!
  Error: Unknown builtin plugin "cleanupIDs" specified.
```
It doesn't matter which icon I am trying to load.

My package json:
```json
{
  "name": "@example/basics",
  "type": "module",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/image": "^0.12.1",
    "@astrojs/netlify": "^1.2.2",
    "@astrojs/partytown": "^1.0.2",
    "@astrojs/sitemap": "^1.0.0",
    "@astrojs/solid-js": "^1.2.3",
    "astro": "^1.6.15",
    "astro-compress": "^1.1.22",
    "astro-icon": "^0.8.0",
    "sharp": "^0.31.2",
    "solid-js": "^1.6.5"
  },
  "devDependencies": {
    "sass": "^1.55.0"
  }
}
```

My Code:
```js
---
import { Icon } from 'astro-icon'
---
<Icon name="carbon:close" />
```

Not sure what's wrong. My last build was a few weeks ago and it worked fine then.

### PR DESCRIPTION
**Pull request by TheOtterlord**
I've gone through the changelog for [SVGO v3](https://github.com/svg/svgo/releases/tag/v3.0.0), and tested my changes with a copy of the demo & an up-to-date Astro v1.8.0 project that used `astro-compress`

- Implement #75 
- Fix #72 
- Fix #65

### CODE REVIEW

**Review by redwerkz — APPROVED** [review]
Looks good to me

@natemoo-re pls have a look at pr

**Review by zoxon — APPROVED** [review]

**Comment by dkotik** [comment]
Please merge :-)

**Review by GrantBirki — APPROVED** [review]

**Comment by stramel** [comment]
I think this would be okay as a minor bump for the existing package code. The `v1` branch already has the SVGO v3 integrated. 

Are there any side-effects from updating to v3?

**Comment by stramel** [comment]
Thanks for this PR! At this time we're going to forego this and focus on the v1 since this has a workaround and we have published a next version of `astro-icon` that includes using `svgo@v3`

**Pull request closed without merging**
